http:
  port: ${PORT:-8080}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  pitstop-customer:
    host: localhost
    paths: '/api/customers/*'
  pitstop-vehicle:
    host: localhost
    paths: '/api/vehicles/*'
  pitstop-workshop:
    host: localhost
    paths: '/api/workshop/*'
serviceEndpoints:
  pitstop-customer-service:
    # url: ${CUSTOMER_URL:-'http://customer-container-service:3001/'}   
    url: ${CUSTOMER_URL:-'http://customer-service:3001/'}
  pitstop-vehicle-service:
    #url: ${CUSTOMER_URL:-'http://vehicle-container-service:3001/'}
    url: ${VEHICLE_URL:-'http://vehicle-service:3002/'}
  pitstop-workshop-service:
    #url: ${CUSTOMER_URL:-'http://workshop-container-service:3001/'}
    url: ${WORKSHOP_URL:-'http://workshop-service:3003/'}

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  customers-pipelines:
    apiEndpoints:
      - pitstop-customer
    policies:
      - cors:
          action:
            origin: "*"
            methods: "GET,HEAD,PUT,PATCH,POST,DELETE"
            preflightContinue: false
            optionsSuccessStatus: 204
      - proxy:
          action:
            serviceEndpoint: pitstop-customer-service
            changeOrigin: true
  vehicles-pipelines:
    apiEndpoints:
      - pitstop-vehicle
    policies:
      - cors:
          action:
            origin: "*"
            methods: "GET,HEAD,PUT,PATCH,POST,DELETE"
            preflightContinue: false
            optionsSuccessStatus: 204
      - proxy:
          action:
            serviceEndpoint: pitstop-vehicle-service
            changeOrigin: true
  workshop-pipelines:
    apiEndpoints:
      - pitstop-workshop
    policies:
      - cors:
          action:
            origin: "*"
            methods: "GET,HEAD,PUT,PATCH,POST,DELETE"
            preflightContinue: false
            optionsSuccessStatus: 204
      - proxy:
          action:
            serviceEndpoint: pitstop-workshop-service
            changeOrigin: true
