apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/medvers-pitstop/kubernetes.git
    targetRevision: HEAD
    path: k8s-manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: garage
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
